name: Build

on: 
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: 'Plugin version'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'
          cache: 'maven'
      - name: Build with Maven
        run: mvn clean install -DpluginVersion=${plg_version}
        env:
          plg_version: ${{ github.event.inputs.version }}
      - uses: rickstaa/action-create-tag@v1
        id: tag_create
        with:
          tag: ${{ github.event.inputs.version }}
          tag_exists_error: false
          message: "release ${{ github.event.inputs.version }}"
      - uses: actions/create-release@v1.0.0
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          draft: false
          prerelease: false
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/AllowMcMember-${{github.event.inputs.version}}.jar
          asset_name: AllowMcMember.jar
          asset_content_type: application/java-archiver
